# Generated by Django 5.2.1 on 2025-05-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(default='joWgbZ', max_length=50, unique=True),
        ),
    ]
