# Generated by Django 5.2.1 on 2025-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_url_count_alter_url_short_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
